# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise64"

  # don't need guest box additions for tests
  config.vbguest.no_install = true
  config.vbguest.no_remote = true

  config.vm.define :puppetmaster do |cfg|
    cfg.vm.host_name = "puppet-master.local"
    cfg.vm.network :hostonly, "192.168.2.10"

    cfg.vm.provision :shell, :path => "scripts/setup-puppet-master.sh"

    cfg.vm.share_folder "manifests", "/etc/puppet/manifests", "manifests"
    cfg.vm.share_folder "modules", "/etc/puppet/modules", "modules"
    cfg.vm.share_folder "secret", "/etc/puppet/modules/secret", "../."    
  end

  config.vm.define :puppetagent do |cfg|
    cfg.vm.host_name = "puppet-agent.local"
    cfg.vm.network :hostonly, "192.168.2.11"

    cfg.vm.provision :shell, :path => "scripts/setup-puppet-agent.sh"
  end
end
