source 'https://rubygems.org'
gem 'puppet',                 '3.2.1'
gem 'puppetlabs_spec_helper', '0.4.1'
gem 'facter',                 '1.7.1'
gem 'rspec-puppet',           '0.1.6'
gem 'rake',                   '10.0.4'
